version: "3.7"

services:
    hello-world-app:
        build: 
            context: .
            dockerfile: Dockerfile
        ports:
            - 5000:5000
        environment:
            - PAGE_TITLE=Page Title
            - SPECIAL_MESSAGE=Special Message
            - HEADER_MESSAGE=Header Message
            - HOST_NAME=Host Name
            - INTERNAL_IP_ADDRESS=192.168.1.100
            - EXTERNAL_IP_ADDRESS=169.95.96.1
            - HOST_OPERATING_SYSTEM=Ubuntu
            - BOOT_TIME=Mon Mar 30 15:19:07 UTC 2020
        volumes:
            - ./app:/app