---
- name: pause for 240 seconds for apt to become available
  pause:
    seconds: 240

- name: update and upgrade apt packages
  apt:
    name: "*"
    state: latest
    update_cache: yes

- name: add required packages for installing docker over https
  apt:
    pkg:
      - apt-transport-https 
      - btrfs-progs
      - ca-certificates 
      - curl 
      - gnupg-agent
      - python3
      - python3-pip
      - software-properties-common

- name: add docker apt gpg key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
    state: present

- name: install docker packages
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: restart and enable docker service
  service:
    name: docker
    state: restarted
    enabled: yes

- name: add ubuntu user to docker group
  user:
    name: "ubuntu"
    append: yes
    groups: docker